openapi: 3.0.0
info:
  title: LMS API
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /api/auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Auth token
  /api/users:
    get:
      summary: List users
      responses:
        '200':
          description: List of users
    post:
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: Created
  /api/courses:
    get:
      summary: List courses
      responses:
        '200':
          description: Courses
    post:
      summary: Create course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '201':
          description: Created
